modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[dependencies.frostvisuals]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.frostvisuals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[mods]]
modId="frostvisuals"
version="2.0.0"
displayName="FrostVisuals"
description='''FrostVisuals 2.0 — Premium Minecraft visual client mod.'''
